spring:
  datasource:
    url: jdbc:mysql://localhost:3306/courseapp?useSSL=false&serverTimezone=UTC
    username: root
    password: Nicat2006
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml


